# Generated by Django 4.0.1 on 2022-01-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_no', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Job #')),
                ('party_dc_no', models.CharField(max_length=20, verbose_name='Party DC #')),
                ('unique_id', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.color')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.partner', verbose_name='Customer')),
                ('status', models.ForeignKey(default='OPEN', on_delete=django.db.models.deletion.CASCADE, to='master.status', verbose_name='Job Status')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.style')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=16, null=True)),
                ('order_date', models.DateField(verbose_name='Order Date')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=30)),
                ('unique_id', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('job_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.job')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.size')),
            ],
        ),
        migrations.CreateModel(
            name='FabricInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=16, null=True)),
                ('party_dc_date', models.DateField(verbose_name='Party DC Date')),
                ('no_of_rolls', models.DecimalField(decimal_places=0, default=0, max_digits=30, verbose_name='No of rolls')),
                ('dc_weight', models.DecimalField(decimal_places=3, default=0, max_digits=30, verbose_name='DC Weight')),
                ('received_weight', models.DecimalField(decimal_places=3, default=0, max_digits=30, verbose_name='Received Weight')),
                ('unique_id', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.color')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.fabrictype')),
                ('job_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.job')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=16, null=True)),
                ('delivery_date', models.DateField(verbose_name='Delivery Date')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=30)),
                ('unique_id', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('job_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.job')),
                ('piece_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.piecetype')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.size')),
            ],
        ),
    ]
