# Generated by Django 4.0.1 on 2022-01-29 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Order Date'),
        ),
    ]
