# Generated by Django 4.0.1 on 2022-01-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_remove_order_order_date_job_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='total_delivery_quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='job',
            name='total_order_quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30),
        ),
    ]
