# Generated by Django 4.0.1 on 2022-01-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_job_total_delivery_quantity_job_total_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_date',
            new_name='date',
        ),
    ]
