# Generated by Django 4.0.1 on 2022-01-30 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_rename_delivery_date_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='total_delivery_quantity',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='total_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=30, null=True),
        ),
    ]
