# Generated by Django 4.0.1 on 2022-04-27 05:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('production', '0005_alter_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricinward',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.color', verbose_name='Fabric Inward Color'),
        ),
        migrations.AlterField(
            model_name='fabricinward',
            name='no_of_rolls',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30, verbose_name='Number of rolls'),
        ),
        migrations.AlterField(
            model_name='fabricinward',
            name='party_dc_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Party DC Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Job Date'),
        ),
    ]
